import React from 'react';

export const About = () => {
  return (
    <main>
      <h1 className="text-3xl font-bold mb-4">About Page</h1>
      <p className="text-lg">This is the about page of our application.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ex repellat iure ratione numquam dolore placeat vitae autem corrupti debitis molestias expedita ea error nostrum impedit est vel in fugit, praesentium architecto omnis esse quasi aliquid. Consequatur nostrum blanditiis architecto doloremque dicta sit optio minus accusamus cum odit facere corporis ab modi quasi autem, alias ipsum dolores, repudiandae harum, amet quis officiis possimus eos nihil! Est impedit eaque blanditiis officia animi, quisquam unde. Aliquam animi consectetur dolore ut excepturi? Voluptates consequuntur quae suscipit assumenda minima harum, nihil, quod dolor autem quibusdam magnam distinctio delectus similique fuga consectetur ipsam veniam aliquid non aperiam. Consequatur, doloribus asperiores voluptates deserunt reprehenderit, eos praesentium perspiciatis dolore ducimus animi veniam nobis molestiae, necessitatibus excepturi facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ex repellat iure ratione numquam dolore placeat vitae autem corrupti debitis molestias expedita ea error nostrum impedit est vel in fugit, praesentium architecto omnis esse quasi aliquid. Consequatur nostrum blanditiis architecto doloremque dicta sit optio minus accusamus cum odit facere corporis ab modi quasi autem, alias ipsum dolores, repudiandae harum, amet quis officiis possimus eos nihil! Est impedit eaque blanditiis officia animi, quisquam unde. Aliquam animi consectetur dolore ut excepturi? Voluptates consequuntur quae suscipit assumenda minima harum, nihil, quod dolor autem quibusdam magnam distinctio delectus similique fuga consectetur ipsam veniam aliquid non aperiam. Consequatur, doloribus asperiores voluptates deserunt reprehenderit, eos praesentium perspiciatis dolore ducimus animi veniam nobis molestiae, necessitatibus excepturi facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ex repellat iure ratione numquam dolore placeat vitae autem corrupti debitis molestias expedita ea error nostrum impedit est vel in fugit, praesentium architecto omnis esse quasi aliquid. Consequatur nostrum blanditiis architecto doloremque dicta sit optio minus accusamus cum odit facere corporis ab modi quasi autem, alias ipsum dolores, repudiandae harum, amet quis officiis possimus eos nihil! Est impedit eaque blanditiis officia animi, quisquam unde. Aliquam animi consectetur dolore ut excepturi? Voluptates consequuntur quae suscipit assumenda minima harum, nihil, quod dolor autem quibusdam magnam distinctio delectus similique fuga consectetur ipsam veniam aliquid non aperiam. Consequatur, doloribus asperiores voluptates deserunt reprehenderit, eos praesentium perspiciatis dolore ducimus animi veniam nobis molestiae, necessitatibus excepturi facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ex repellat iure ratione numquam dolore placeat vitae autem corrupti debitis molestias expedita ea error nostrum impedit est vel in fugit, praesentium architecto omnis esse quasi aliquid. Consequatur nostrum blanditiis architecto doloremque dicta sit optio minus accusamus cum odit facere corporis ab modi quasi autem, alias ipsum dolores, repudiandae harum, amet quis officiis possimus eos nihil! Est impedit eaque blanditiis officia animi, quisquam unde. Aliquam animi consectetur dolore ut excepturi? Voluptates consequuntur quae suscipit assumenda minima harum, nihil, quod dolor autem quibusdam magnam distinctio delectus similique fuga consectetur ipsam veniam aliquid non aperiam. Consequatur, doloribus asperiores voluptates deserunt reprehenderit, eos praesentium perspiciatis dolore ducimus animi veniam nobis molestiae, necessitatibus excepturi facilis.</p>
    </main>

  );
};